# Generated by Django 5.0 on 2023-12-29 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions_model',
            name='type',
            field=models.IntegerField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw'), ('LOAN_REQUEST', 'Loan Request'), ('LOAN_PAID', 'Loan Paid')], null=True),
        ),
    ]
