# Generated by Django 5.0 on 2023-12-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transactions_model_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions_model',
            name='type',
            field=models.IntegerField(choices=[(1, 'Deposit'), (2, 'Withdraw'), (3, 'Loan Request'), (4, 'Loan Paid')], null=True),
        ),
    ]
