# Generated by Django 5.0 on 2024-01-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transactions_model_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions_model',
            name='type',
            field=models.IntegerField(choices=[(1, 'Deposit'), (2, 'Withdraw'), (3, 'Loan Request'), (4, 'Loan Paid'), (5, 'Transfer')], null=True),
        ),
    ]
