# Generated by Django 5.0 on 2024-01-04 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('transactions', '0004_alter_transactions_model_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions_model',
            name='receiver_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_transactions', to='accounts.userbankaccount_model'),
        ),
        migrations.AlterField(
            model_name='transactions_model',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.userbankaccount_model'),
        ),
    ]
