# Generated by Django 5.0 on 2024-01-04 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('transactions', '0005_transactions_model_receiver_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions_model',
            name='receiver_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_transactions', to='accounts.userbankaccount_model'),
        ),
    ]
